name: 
on: 
  # workflow_dispatch
  # 每天早上7-8点执行(北京时间)
  schedule:
    - cron: "0 23 * * *"

jobs:
  novel:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/checkout@v3
      - name: run python
        run: python dailyWork.py
        env:
          email_token: ${{ secrets.EMAIL_TOKEN }}
