name: daily work
on: 
   workflow_dispatch
  # 每天早上7-8点执行(北京时间)
#   schedule:
#     - cron: "0 23 * * *"

jobs:
  novel:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/checkout@v3
      - name: install 
        run: pip install lxml
      - name: run python
        run: python dailyWork.py
        env:
          email_token: ${{ secrets.EMAIL_TOKEN }}
      - name: commit log
        run: |
          git config --local user.email '3504448058@qq.com'
          git config --local user.name 'liubai-icu'
          git add ./log.txt
          git commit -m 'add update' || git diff --exit-code
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
