name: get latest novel
on: workflow_dispatch
jobs:
  novel:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/checkout@v3
      - name: install
        run: pip install lxml
      - name: run python
        run: python novel.py
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
