name: latest novel
on: 
  workflow_dispatch
#   schedule:
#     - cron: "0 * * * *"

jobs:
  novel:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/checkout@v3
      - name: install
        run: pip install lxml
      - name: run python
        run: python novel.py
        env:
          email_token: ${{ secrets.EMAIL_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
