name: get latest novel
on: workflow_dispatch
jobs:
  novel:
    runs-on: ubuntu-latest
    steps:
      - name: set up
        uses: actions/checkout@v3
      - name: install
        run: pip install lxml
      - name: run python
        run: python novel.py
      - name: Push local repository changes
        id: push-local-repository-changes
        uses: reloc8/action-push-local-changes@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          commit-message: 'Create new file'
